import View.listaConflitos;
import View.listaGrupoArmado;
import View.listaOrg;
import View.listaPaisNr;
import View.listaTraficantes;
import dao.Conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author rober
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_cadastroDivMilitar = new javax.swing.JButton();
        divisoes = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        grupoMilitar = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        grafico = new javax.swing.JButton();
        listaTrafGrupArm = new javax.swing.JButton();
        maioresConflitos = new javax.swing.JButton();
        listaMaioresOrg = new javax.swing.JButton();
        listaMaiorGrupoArmado = new javax.swing.JButton();
        listaPais = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 153));

        btn_cadastroDivMilitar.setText("Cadastrar");
        btn_cadastroDivMilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastroDivMilitarActionPerformed(evt);
            }
        });

        divisoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisoesActionPerformed(evt);
            }
        });

        grupoMilitar.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(grupoMilitar);

        jLabel1.setText("Cadastro de divisões dentro de um grupo militar");

        jLabel2.setText("Listagens");

        grafico.setText("Gráfico");
        grafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graficoActionPerformed(evt);
            }
        });

        listaTrafGrupArm.setText("Lista de traficantes e grupos armados");
        listaTrafGrupArm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaTrafGrupArmActionPerformed(evt);
            }
        });

        maioresConflitos.setText("Lista dos 5 maiores conflitos");
        maioresConflitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maioresConflitosActionPerformed(evt);
            }
        });

        listaMaioresOrg.setText("Lista das 5 maiores organizações");
        listaMaioresOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaMaioresOrgActionPerformed(evt);
            }
        });

        listaMaiorGrupoArmado.setText("Lista dos 5 maiories grupos armados");
        listaMaiorGrupoArmado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaMaiorGrupoArmadoActionPerformed(evt);
            }
        });

        listaPais.setText("Lista do país");
        listaPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaPaisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listaPais)
                    .addComponent(listaMaiorGrupoArmado)
                    .addComponent(listaMaioresOrg)
                    .addComponent(maioresConflitos)
                    .addComponent(listaTrafGrupArm)
                    .addComponent(btn_cadastroDivMilitar)
                    .addComponent(grafico)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divisoes, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(171, 171, 171))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(divisoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_cadastroDivMilitar)
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(14, 14, 14)
                .addComponent(grafico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listaTrafGrupArm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(maioresConflitos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listaMaioresOrg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listaMaiorGrupoArmado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listaPais)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastroDivMilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastroDivMilitarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "O cadastro de divisão dentro do Grupo Militar foi realizado"+divisoes.getText());
    }//GEN-LAST:event_btn_cadastroDivMilitarActionPerformed

    private void divisoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisoesActionPerformed
     

    }//GEN-LAST:event_divisoesActionPerformed

    private void graficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graficoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_graficoActionPerformed

    private void listaTrafGrupArmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaTrafGrupArmActionPerformed
        // TODO add your handling code here:
        listaTraficantes telaTraficantes = new listaTraficantes();
        telaTraficantes.setVisible(true);
        
       
    }//GEN-LAST:event_listaTrafGrupArmActionPerformed

    private void listaMaioresOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaMaioresOrgActionPerformed
        // TODO add your handling code here:
        listaOrg telaMaioresOrg = new listaOrg();
        telaMaioresOrg.setVisible(true);
    }//GEN-LAST:event_listaMaioresOrgActionPerformed

    private void maioresConflitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maioresConflitosActionPerformed
        // TODO add your handling code here:
        listaConflitos telaListaConflitos = new listaConflitos();
        telaListaConflitos.setVisible(true);
        
        
    }//GEN-LAST:event_maioresConflitosActionPerformed

    private void listaMaiorGrupoArmadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaMaiorGrupoArmadoActionPerformed
        // TODO add your handling code here:
        listaGrupoArmado telaListaGrupoArmado = new listaGrupoArmado();
        telaListaGrupoArmado.setVisible(true);
    }//GEN-LAST:event_listaMaiorGrupoArmadoActionPerformed

    private void listaPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaPaisActionPerformed
        // TODO add your handling code here:
        listaPaisNr telaPaisNrConfl = new listaPaisNr();
        telaPaisNrConfl.setVisible(true);
    }//GEN-LAST:event_listaPaisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        
      
        
        
 
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastroDivMilitar;
    private javax.swing.JTextField divisoes;
    private javax.swing.JButton grafico;
    private javax.swing.JList<String> grupoMilitar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton listaMaiorGrupoArmado;
    private javax.swing.JButton listaMaioresOrg;
    private javax.swing.JButton listaPais;
    private javax.swing.JButton listaTrafGrupArm;
    private javax.swing.JButton maioresConflitos;
    // End of variables declaration//GEN-END:variables
}
